apiVersion: apps/v1
kind: Deployment
metadata:
  name: bssdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bssdb
  template:
    metadata:
      labels:
        component: bssdb
    spec:
      containers:
        - name: bssdb
          image: ranjanra/bssdb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbrootpassword
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: password
            - name: MYSQL_DATABASE
              value: wdp
            - name: MYSQL_USER
              value: wdp
          ports:
            - containerPort: 3306
